- name: Deploy stack
  docker_stack:
          state: present
          name: char-gen
          compose:
                  - /home/agrisjakob/char-gen/docker-compose.yaml
  environment:
                  DATABASE_URI: "{{ DATABASE_URI }}"
