          - name: "Install dependencies"
            apt:
                    pkg:
                            - apt-transport-https
                            - ca-certificates
                            - curl
                            - gnupg-agent
                            - software-properties-common
                            - python3
                            - python3-pip
                            - python3-venv
                    update_cache: yes
                    state: latest
          - name: pip install docker-py
            pip:
                    name: 
                    - docker-py
                    - jsondiff
          - name: "Add Docker Key"
            apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
                    state: present
          - name: "Add Docker repo"
            apt_repository:
                    repo: deb https://download.docker.com/linux/ubuntu bionic stable
                    state: present
          - name: "Install Docker Engine"
            apt:
                    pkg:
                            - docker-ce
                            - docker-ce-cli
                            - containerd.io
                    update_cache: yes
                    state: latest
          - name: "Add user to docker grop"
            user:
                    name: docker
                    shell: /bin/bash
                    group: docker
                    state: present



