- hosts: managers, workers
  become: yes
  roles:
          - common
- hosts: managers
  become: yes
  roles:
          - master
- hosts: workers
  become: yes
  roles:
          - workers
- hosts: managers
  become: yes
  roles:
          - deploy

- hosts: nginx
  become: yes
  roles:
          - nginx
