- name: install nginx
  apt:
          pkg:
                  - nginx
          state: latest
          update_cache: true


- name: add nginx.conf file
  template:
          src: ./nginx.conf
          dest: /etc/nginx/nginx.conf
  register: nginx_config

- name: start nginx
  service:
          name: nginx
          state: started

- name: reload nginx
  service:
          name: nginx
          state: reloaded
  when: nginx_config.changed


